services:
  # PostgreSQL Database (Development)
  postgres:
    image: postgres:15-alpine
    container_name: aiagent-postgres
    environment:
      POSTGRES_USER: aiagent
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiagent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiagent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiagent-network

  # PostgreSQL Database (Testing)
  postgres-test:
    image: postgres:15-alpine
    container_name: aiagent-postgres-test
    environment:
      POSTGRES_USER: aiagent_test
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: aiagent_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiagent_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiagent-network
    profiles:
      - test

  # Redis
  redis:
    image: redis:7-alpine
    container_name: aiagent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiagent-network

  # pgAdmin - PostgreSQL Management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aiagent-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aiagent.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-pgpass:/tmp/pgpassfile:ro
    networks:
      - aiagent-network
    depends_on:
      postgres:
        condition: service_healthy

  # API Service (OPTIONAL - Run locally for Claude Code CLI access)
  # NOTE: API should run locally, not in Docker, to access Claude Code subsystem
  # Use 'make start' to run API locally with Docker infrastructure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiagent-api
    environment:
      DATABASE_URL: postgresql+asyncpg://aiagent:password@postgres:5432/aiagent_db
      REDIS_URL: redis://redis:6379/0
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      SECRET_KEY: ${SECRET_KEY:-your_secret_key_here_minimum_32_characters_long}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      DEBUG: ${DEBUG:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - aiagent-network
    restart: unless-stopped
    profiles:
      - full-docker  # Only start with --profile full-docker

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
  pgadmin_data:

networks:
  aiagent-network:
    driver: bridge
